language: java


jdk:
  - openjdk11


install: true

branches:
  only:
    - develop

cache:
  directories:
    - $HOME/.m2

script:
  - git clone https://github.com/binance-exchange/binance-java-api.git && cd  binance-java-api && mvn clean install && cd ..
  - mvn clean compile > /dev/null 2>&1
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent test
  - mvn cobertura:cobertura

env:
  - CODECOV_TOKEN='dc721415-acfd-481c-a721-0800001ee0b4'

after_success:
  - bash <(curl -s https://codecov.io/bash)
